export const elementsInfo = [
  { sym: "X", class: "X" },
  { sym: "H", class: "H" },
  { sym: "He", class: "noble" },
  { sym: "Li", class: "alkali" },
  { sym: "Be", class: "alkaline_earth" },
  { sym: "B", class: "semimetal" },
  { sym: "C", class: "nonmetal" },
  { sym: "N", class: "nonmetal" },
  { sym: "O", class: "nonmetal" },
  { sym: "F", class: "halogen" },
  { sym: "Ne", class: "noble" },
  { sym: "Na", class: "alkali" },
  { sym: "Mg", class: "alkaline_earth" },
  { sym: "Al", class: "post_transition" },
  { sym: "Si", class: "semimetal" },
  { sym: "P", class: "nonmetal" },
  { sym: "S", class: "nonmetal" },
  { sym: "Cl", class: "halogen" },
  { sym: "Ar", class: "noble" },
  { sym: "K", class: "alkali" },
  { sym: "Ca", class: "alkaline_earth" },
  { sym: "Sc", class: "transition" },
  { sym: "Ti", class: "transition" },
  { sym: "V", class: "transition" },
  { sym: "Cr", class: "transition" },
  { sym: "Mn", class: "transition" },
  { sym: "Fe", class: "transition" },
  { sym: "Co", class: "transition" },
  { sym: "Ni", class: "transition" },
  { sym: "Cu", class: "transition" },
  { sym: "Zn", class: "transition" },
  { sym: "Ga", class: "post_transition" },
  { sym: "Ge", class: "semimetal" },
  { sym: "As", class: "semimetal" },
  { sym: "Se", class: "nonmetal" },
  { sym: "Br", class: "halogen" },
  { sym: "Kr", class: "noble" },
  { sym: "Rb", class: "alkali" },
  { sym: "Sr", class: "alkaline_earth" },
  { sym: "Y", class: "transition" },
  { sym: "Zr", class: "transition" },
  { sym: "Nb", class: "transition" },
  { sym: "Mo", class: "transition" },
  { sym: "Tc", class: "transition" },
  { sym: "Ru", class: "transition" },
  { sym: "Rh", class: "transition" },
  { sym: "Pd", class: "transition" },
  { sym: "Ag", class: "transition" },
  { sym: "Cd", class: "transition" },
  { sym: "In", class: "post_transition" },
  { sym: "Sn", class: "post_transition" },
  { sym: "Sb", class: "semimetal" },
  { sym: "Te", class: "semimetal" },
  { sym: "I", class: "halogen" },
  { sym: "Xe", class: "noble" },
  { sym: "Cs", class: "alkali" },
  { sym: "Ba", class: "alkaline_earth" },
  { sym: "La", class: "lanthanoid" },
  { sym: "Ce", class: "lanthanoid" },
  { sym: "Pr", class: "lanthanoid" },
  { sym: "Nd", class: "lanthanoid" },
  { sym: "Pm", class: "lanthanoid" },
  { sym: "Sm", class: "lanthanoid" },
  { sym: "Eu", class: "lanthanoid" },
  { sym: "Gd", class: "lanthanoid" },
  { sym: "Tb", class: "lanthanoid" },
  { sym: "Dy", class: "lanthanoid" },
  { sym: "Ho", class: "lanthanoid" },
  { sym: "Er", class: "lanthanoid" },
  { sym: "Tm", class: "lanthanoid" },
  { sym: "Yb", class: "lanthanoid" },
  { sym: "Lu", class: "lanthanoid" },
  { sym: "Hf", class: "transition" },
  { sym: "Ta", class: "transition" },
  { sym: "W", class: "transition" },
  { sym: "Re", class: "transition" },
  { sym: "Os", class: "transition" },
  { sym: "Ir", class: "transition" },
  { sym: "Pt", class: "transition" },
  { sym: "Au", class: "transition" },
  { sym: "Hg", class: "transition" },
  { sym: "Tl", class: "post_transition" },
  { sym: "Pb", class: "post_transition" },
  { sym: "Bi", class: "post_transition" },
  { sym: "Po", class: "post_transition" },
  { sym: "At", class: "halogen" },
  { sym: "Rn", class: "noble" },
  { sym: "Fr", class: "alkali" },
  { sym: "Ra", class: "alkaline_earth" },
  { sym: "Ac", class: "actinoid" },
  { sym: "Th", class: "actinoid" },
  { sym: "Pa", class: "actinoid" },
  { sym: "U", class: "actinoid" },
  { sym: "Np", class: "actinoid" },
  { sym: "Pu", class: "actinoid" },
  { sym: "Am", class: "actinoid" },
  { sym: "Cm", class: "actinoid" },
  { sym: "Bk", class: "actinoid" },
  { sym: "Cf", class: "actinoid" },
  { sym: "Es", class: "actinoid" },
  { sym: "Fm", class: "actinoid" },
  { sym: "Md", class: "actinoid" },
  { sym: "No", class: "actinoid" },
  { sym: "Lr", class: "actinoid" },
  { sym: "Rf", class: "transition" },
  { sym: "Db", class: "transition" },
  { sym: "Sg", class: "transition" },
  { sym: "Bh", class: "transition" },
  { sym: "Hs", class: "transition" },
  { sym: "Mt", class: "X" },
  { sym: "Ds", class: "X" },
  { sym: "Rg", class: "X" },
  { sym: "Cn", class: "X" },
  { sym: "Nh", class: "X" },
  { sym: "Fl", class: "X" },
  { sym: "Mc", class: "X" },
  { sym: "Lv", class: "X" },
  { sym: "Ts", class: "X" },
  { sym: "Og", class: "X" },
];

// color inspiration from http://www.pseudo-dojo.org/
export const elementClassColors = {
  X: "rgb(220, 220, 220)",
  H: "rgb(220, 105, 105)",
  noble: "rgb(196, 205, 255)",
  alkali: "rgb(209, 146, 146)",
  alkaline_earth: "rgb(209, 189, 146)",
  semimetal: "rgb(189, 214, 163)",
  nonmetal: "rgb(214, 163, 190)",
  halogen: "rgb(210, 214, 163)",
  post_transition: "rgb(163, 178, 214)",
  transition: "rgb(169, 196, 212)",
  lanthanoid: "rgb(237, 184, 255)",
  actinoid: "rgb(191, 150, 255)",
};
